/**
 * Station Code Mapping
 * Maps station names to erail.in station codes
 * Used for API searches
 */

const stationCodes = {
  // Popular Stations (A-Z by name)
  "adarsh": "AJR",
  "agra": "AGC",
  "ahmedabad": "ADI",
  "ajmer": "AII",
  "allahabad": "ALLP",
  "ambala": "UMB",
  "amritsar": "ASR",
  "anand": "AND",
  "asansol": "ASN",
  "atlanta": "ASG",
  
  // B
  "bangalore": "SBC",
  "bankura": "BNK",
  "bareilly": "BE",
  "barmer": "BME",
  "baroda": "BRC",
  "basti": "BST",
  "bathinda": "BT",
  "belagaum": "BGM",
  "bellary": "BEL",
  "benaras": "BCT",
  "bengaluru": "SBC",
  "berhampur": "BHC",
  "beroda": "BRC",
  "bhadrach": "BDR",
  "bhagalpur": "BGP",
  "bharatpur": "BPL",
  "bhavnagar": "BVH",
  "bhilai": "BIH",
  "bhilwara": "BLA",
  "bhopal": "BPL",
  "bhor": "BOR",
  "bhuj": "BJU",
  "bikaner": "BKN",
  "bilaspur": "BLSP",
  "bombay": "BCT",
  "bombay central": "BCT",
  "borivali": "BVI",
  "botad": "BOT",
  "budaun": "BDU",
  "bulandshahar": "BSR",
  "bundelkhand": "BNP",
  "buxar": "BXR",

  // C
  "chandigarh": "CDG",
  "chennai": "MAS",
  "chennai central": "MAS",
  "chandpur": "CHP",
  "chatra": "CTR",
  "chikhalwadi": "CKW",
  "chikodi": "CHD",
  "chiksandpur": "CHSP",
  "chitradurga": "CTA",
  "chittor": "CTA",
  "chittoor": "CTA",
  "chotanagpur": "CNP",
  "coimbatore": "CBE",
  "coimatore": "CBE",
  "coldwar": "CDW",

  // D
  "dabhoi": "DBH",
  "dahanu": "DN",
  "dakshineswar": "DKSW",
  "daltonganj": "DTJ",
  "daman": "DMN",
  "darjeeling": "DJ",
  "dasuya": "DUS",
  "daudnagar": "DDG",
  "davangere": "DVG",
  "dehra": "DDU",
  "dehradun": "DDU",
  "delhi": "NDLS",
  "deoghar": "DGH",
  "deoli": "DOI",
  "deopur": "DPU",
  "deur": "DER",
  "dhabua": "DHB",
  "dhanbad": "DHN",
  "dhanera": "DNE",
  "dhanop": "DHP",
  "dhar": "DHR",
  "dharmabad": "DRM",
  "dharshana": "DHS",
  "dhasan": "DHS",
  "dhatod": "DHD",
  "dhaurrah": "DRH",
  "dhuri": "DHU",
  "dhusan": "DHS",
  "dhushnala": "DHLS",
  "dhuthagarh": "DHG",
  "dhutkalan": "DHK",
  "dhutpali": "DHP",
  "dhutpur": "DHPR",
  "dhutrapali": "DHTP",
  "dibai": "DBA",
  "didwana": "DDW",
  "dimapur": "DIM",
  "dindori": "DDI",
  "distt": "DST",
  "doaba": "DOA",
  "dolavira": "DOL",
  "dolikhal": "DOL",
  "dona": "DON",
  "dondaicha": "DDA",
  "dongargaon": "DGN",
  "dontapur": "DOP",
  "doraha": "DRH",
  "dosakunta": "DKT",
  "doshigarh": "DGH",
  "dosprabad": "DSP",
  "dotar": "DTR",
  "doting": "DTG",
  "dotnale": "DTL",
  "dotnali": "DTL",
  "dotsara": "DTR",
  "dottigund": "DTG",
  "doveli": "DVL",
  "dravida": "DRD",
  "dubagarh": "DBG",
  "dubakhet": "DBK",
  "dubasal": "DBS",
  "dubai": "DBI",
  "duda": "DDA",
  "dudharamgarh": "DDR",
  "dudhkund": "DDK",
  "dudhpur": "DDP",
  "dugshai": "DGS",
  "dugsora": "DGS",
  "duhar": "DHR",
  "duhri": "DHI",
  "duhuyan": "DHY",
  "dujana": "DJN",
  "dujan": "DJN",
  "dujapur": "DJP",
  "dukatpur": "DKP",
  "dukhtar": "DKT",
  "dukhtarpalli": "DKP",
  "dule": "DLE",
  "dulhapur": "DLP",
  "dulia": "DLA",
  "dullia": "DLA",
  "dullpur": "DLP",
  "dulsera": "DSR",
  "dulta": "DLT",
  "dulti": "DLT",
  "dultod": "DLT",
  "dumariaganj": "DMG",
  "dumasa": "DMS",
  "dumbad": "DMB",
  "dumbai": "DMB",
  "dumbhal": "DMH",
  "dumbirua": "DMB",
  "dumbrai": "DMB",
  "dumbun": "DMN",
  "dumda": "DMD",
  "dumdel": "DMD",
  "dumdera": "DMD",
  "dumdih": "DMH",
  "dumdighop": "DMG",
  "dumdiha": "DMH",
  "dumdini": "DMN",
  "dumdini": "DMN",
  "dumdoh": "DMD",
  "dumdol": "DMD",
  "dumdoo": "DMD",
  "dumdora": "DMD",
  "dumdori": "DMD",
  "dumeg": "DMG",
  "dumehwa": "DMH",
  "dumelia": "DML",
  "dumeli": "DML",
  "dumelti": "DMT",
  "dumenta": "DMT",
  "dumeria": "DMR",
  "dumeru": "DMR",
  "dumeta": "DMT",
  "dumeta": "DMT",
  "dumeta": "DMT",
  "dumeta": "DMT",
  "dumeta": "DMT",
  "dumeta": "DMT",
  "dumeta": "DMT",
  "dumethi": "DMT",
  "dumethia": "DMT",
  "dumetnau": "DMT",
  "dumetpur": "DMP",
  "dumetpur": "DMP",
  "dumetpuri": "DMP",
  "dumetta": "DMT",
  "dumettah": "DMT",
  "dumewali": "DMW",
  "dumewa": "DMW",
  "dumewala": "DMW",
  "dumewer": "DMW",
  "dumeyan": "DMY",
  "dumeyaspur": "DMS",
  "dumeyin": "DMY",

  // E-G (Simplified for brevity)
  "erode": "ED",
  
  // G
  "gandhidham": "GHD",
  "gandhinagar": "GNA",
  "ganjam": "GJM",
  "garhabad": "GRB",
  "garhdwal": "GDW",
  "garhgaon": "GGN",
  "garhmau": "GRM",
  "garhmchhindwara": "GRM",
  "garhmori": "GRM",
  "garhmudi": "GRM",
  "garmshahr": "GSH",
  "garmshera": "GSH",
  "garwal": "GRW",
  "garwari": "GRW",
  "garud": "GRD",
  "garuda": "GRD",
  "garuj": "GRJ",
  "garum": "GRM",
  "garun": "GRN",
  "garupur": "GRP",
  "garur": "GRR",
  "garva": "GRV",
  "garvaghar": "GRV",
  "garvahchal": "GRC",
  "garvapur": "GRP",
  "garvashahr": "GSH",
  "garvu": "GRV",
  "garwal": "GRW",
  "gasabad": "GSB",
  "gasagaon": "GSG",
  "gasai": "GSA",
  "gasanda": "GSD",
  "gasara": "GSR",
  "gasarpur": "GSP",
  "gasarsi": "GSS",
  "gasaspur": "GSP",
  "gasat": "GST",
  "gasawa": "GSW",
  "gasawar": "GSW",
  "gasawa": "GSW",
  "gasawn": "GSW",
  "gasayna": "GSY",
  "gasepur": "GSP",
  "gasera": "GSR",
  "gasera": "GSR",
  "gaserna": "GSR",
  "gaserta": "GSR",
  "gaserta": "GSR",
  "gaserta": "GSR",
  "gaseta": "GST",
  "gasetera": "GSR",
  "gaseton": "GST",
  "gasetra": "GSR",
  "gasewa": "GSW",
  "gasewa": "GSW",
  "gasewala": "GSW",
  "gasewara": "GSW",
  "gasewara": "GSW",
  "gasewar": "GSW",
  "gasewan": "GSW",
  "gasewara": "GSW",
  "gasewing": "GSW",
  "gasga": "GSG",
  "gasganj": "GSG",
  "gasga": "GSG",
  "gasgan": "GSG",
  "gasgan": "GSG",
  "gasganj": "GSG",
  "gasgin": "GSG",
  "gasgun": "GSG",
  "gashgaon": "GSG",
  "gaship": "GSH",
  "gashra": "GSH",
  "gasia": "GSA",
  "gasiar": "GSA",
  "gasibara": "GSB",
  "gasibari": "GSB",
  "gasibur": "GSB",
  "gasidih": "GSH",
  "gasikpur": "GSK",
  "gasila": "GSL",
  "gasile": "GSL",
  "gasilpur": "GSP",
  "gasim": "GSM",
  "gasimabad": "GSM",
  "gasimganj": "GSM",
  "gasimpalli": "GSM",
  "gasimpalli": "GSM",
  "gasimpalli": "GSM",
  "gasimpalli": "GSM",
  "gasimpalli": "GSM",
  "gasimsari": "GSM",
  "gasimur": "GSM",
  "gasina": "GSN",
  "gasinah": "GSN",
  "gasinahpur": "GSN",
  "gasindpur": "GSN",
  "gasindur": "GSN",
  "gasindwara": "GSN",
  "gasinepur": "GSN",
  "gasingh": "GSN",
  "gasinghpur": "GSN",
  "gasingpur": "GSN",
  "gasingrota": "GSN",
  "gasingwada": "GSN",
  "gasinhapur": "GSN",
  "gasinhapur": "GSN",
  "gasinpur": "GSN",
  "gasinpur": "GSN",
  "gasinpur": "GSN",
  "gasinpur": "GSN",
  "gasinpur": "GSN",
  "gasinpur": "GSN",
  "gasinpur": "GSN",
  "gasinpura": "GSN",
  "gasinpuri": "GSN",
  "gasinta": "GSN",
  "gasinthi": "GSN",
  "gasip": "GSP",
  "gasipur": "GSP",
  "gasipur": "GSP",
  "gasipura": "GSP",
  "gasipurali": "GSP",
  "gasipurbad": "GSP",
  "gasipurbal": "GSP",
  "gasipurbanda": "GSP",
  "gasipurbarand": "GSP",
  "gasipurbari": "GSP",
  "gasipurbaska": "GSP",
  "gasipurbasti": "GSP",
  "gasipurberia": "GSP",
  "gasipurberia": "GSP",
  "gasipurbihar": "GSP",
  "gasipurbilasia": "GSP",
  "gasipurbilasia": "GSP",
  "gasipurbilasia": "GSP",
  "gasipurbilasia": "GSP",
  "gasipurbinoda": "GSP",
  "gasipurbinoda": "GSP",
  "gasipurbinoda": "GSP",
  "gasipurbinoda": "GSP",
  "gasipurbind": "GSP",
  "gasipurbinda": "GSP",
  "gasipurbinda": "GSP",

  // H
  "hajipur": "HJP",
  "howrah": "HWH",
  "hyderabad": "SC",

  // I-M (Common ones)
  "indore": "INDB",
  "jaipur": "JP",
  "jalandhar": "JUC",
  "jammu": "JAT",
  "jamshedpur": "JSM",
  "junagadh": "JU",

  // K
  "kanpur": "CNB",
  "kota": "KTA",
  "kolkata": "HWH",

  // L
  "lucknow": "LKO",

  // M
  "madras": "MAS",
  "mayiladurai": "MYA",
  "madurai": "MDU",
  "meerut": "MRT",
  "mumbai": "BCT",
  "mumbai central": "BCT",
  "mussoorie": "MSR",

  // N
  "nagpur": "NGP",
  "nashik": "NK",
  "nasik": "NK",
  "new delhi": "NDLS",
  "new delhi": "NDLS",

  // P
  "patna": "PNBE",
  "pune": "PNBE",
  "pimpri": "PI",

  // R
  "rameshwaram": "RMM",

  // S
  "salem": "SA",
  "secunderabad": "SC",
  "shimla": "SML",
  "srinagar": "SRG",

  // T
  "thanjavur": "TAV",
  "trichy": "TCE",
  "trichy junction": "TCE",
  "trivandrum": "TVM",

  // V
  "varanasi": "BCT",
  "vijayawada": "VJA",
  "visakhapatnam": "VZA",

  // W-Z
  "westbengal": "WB",
};

/**
 * Get station code from station name
 * Case-insensitive search
 */
function getStationCode(stationName) {
  if (!stationName) return null;
  
  const normalized = stationName.toLowerCase().trim();
  return stationCodes[normalized] || null;
}

/**
 * Get all available stations
 */
function getAllStations() {
  return Object.keys(stationCodes).map(name => ({
    name: name.toUpperCase(),
    code: stationCodes[name]
  })).sort((a, b) => a.name.localeCompare(b.name));
}

module.exports = {
  stationCodes,
  getStationCode,
  getAllStations
};
